name: Build and Test React App

on:
  push:
    branches: '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Get Current Date"
        id: today
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo ${{env.date}}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
