name: Build and Test React App

on:
  push:
    branches: '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Get Current Date"
        id: today
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
